<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QSIH-00619" ignored="0" name="Default test" tests="1" failures="1" timestamp="13 Feb 2018 08:56:43 GMT" time="525.305" errors="0">
  <testcase name="chart_GetPatienMedSumCollective_TC1" time="525.289" classname="com.testscripts.Chart_GetPatienMedSumCollective_TC1">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test case fails with data: {Med1=D27CBAE7-F21D-436C-B496-D8EF98D4DB2B, Med2=B3A2509A-FBC8-418F-9473-DE2104CA10DC, personId=0DECB38F-B7BC-48C7-B6DF-EC02B0ECA0EE, encounterId=DDAFA91B-6B6D-4242-8657-BA1EDAB803E6}">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Test case fails with data: {Med1=D27CBAE7-F21D-436C-B496-D8EF98D4DB2B, Med2=B3A2509A-FBC8-418F-9473-DE2104CA10DC, personId=0DECB38F-B7BC-48C7-B6DF-EC02B0ECA0EE, encounterId=DDAFA91B-6B6D-4242-8657-BA1EDAB803E6}
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.testscripts.Chart_GetPatienMedSumCollective_TC1.chart_GetPatienMedSumCollective_TC1(Chart_GetPatienMedSumCollective_TC1.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- chart_GetPatienMedSumCollective_TC1 -->
</testsuite> <!-- Default test -->
